config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :tasks

  # get '/tasks'            => 'tasks#index'
  # get '/tasks/new'        => 'tasks#new'
  # get '/task/:id'        => 'tasks#show'
  # post '/tasks'           => 'tasks#index'
  # get '/tasks/:id/edit'   => 'tasks#edit'
  # patch '/tasks/:id'      => 'tasks#update'
  # delete '/tasks/:id'     => 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_tasks, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
  end

  private

  def task_params
    params.require(:task).permit(:name, :description)
  end

  def set_tasks
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3 task-form">
    <%= form_for @task do |f|%>
      <%= f.label :name  %>
      <%= f.text_field :name, class:"form-control" %>
      <%= f.label :description %>
      <%= f.text_area :description, rows: "5",class:"form-control"  %>
      <%= f.submit class:"btn btn-success form-control form-btn" %>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<h1 class="text-center ">Edit Task</h1>

<%= render "form"  %>

app/views/tasks/index.html.erb
<div class="row">
 <h1 class="text-center"> Liste des taches</h1>
  <div class="col-sm-6 col-sm-offset-3 list-task">
    <% @tasks.each do |task| %>
      <h3><%= task.name %></h3>
      <%=link_to "See task",task_path(task), class:"btn btn-success btn-sm"  %>
    <% end %>
  </div>
</div>

app/views/tasks/new.html.erb
<h1 class="text-center ">Create Task</h1>

<%= render "form" %>

app/views/tasks/show.html.erb
<div class="row">

  <div class="col-sm-6 col-sm-offset-3">

    <h3><%= @task.name %></h3>
    <p><%=  @task.description %></p>
    <%=link_to "Back to all task", tasks_path, class:"btn btn-primary"  %>
    <%=link_to "Edit task", edit_task_path, class:"btn btn-warning"  %>
    <%=link_to "Remove", task_path, method: :delete, class:"btn btn-danger"  %>

  </div>
</div>